### ISSUE TITLE
[PROBLEM] MVVM에 해당하는 아키텍쳐에 대한 고민

### ISSUE THREAD

**Issue by RedForest0607** [RedForest0607/riverpod-study#1]
## 🤔 Describe issues
*문제점에 대해 설명해주세요*
- 현재 프로젝트는 MVVM에 빗겨나간 아키텍쳐로, 전체 구조를 MVVM으로 변경하고자 함
- MVVM의 M - VM - V 의 분리도를 riverpod에서 충분하게 제공하지 못한다고 생각이 됨. ex)ref.watch후 provider의 값을 직접 꺼내 쓰는 부분
- riverpod의 문제인지, MVVM의 타협점인지에 대한 논의 필요

## 👉 Issue number or link
*참고할만한 링크들을 아래에 달아주세요*
- https://github.com/huskyjp/flutter-mvvp-riverpod-architecture/blob/main/lib/ui/user_view_model.dart

**Comment by RedForest0607** [comment]
선언적 UI에 MVVM은 필요로 하지 않는다로 종결짓겠습니다

**Comment by rogueEntity** [comment]
선언적 UI에 MVVM 패턴이 적합하지 않은 것은 아니고 riverpod의 구현 방향성과 MVVM 패턴이 상충하는 부분이 있는 것으로 봐야 하지 않을까요

**Comment by RedForest0607** [comment]
> 선언적 UI에 MVVM 패턴이 적합하지 않은 것은 아니고 riverpod의 구현 방향성과 MVVM 패턴이 상충하는 부분이 있는 것으로 봐야 하지 않을까요

선언형을 사용하는 프레임워크에서 MVVM의 유용성에 대해서 의문을 제기하는 사람들이 꽤 있어서요
https://medium.com/@karamage/stop-using-mvvm-with-swiftui-2c46eb2cc8dc
https://developer.apple.com/forums/thread/699003

**Comment by rogueEntity** [comment]
confirmed.

**Comment by RedForest0607** [comment]
멋있게 영어로 코멘트 달기 금지금지
